name: CICD PIPELINE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.YOUR_EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.YOUR_EC2_PUBLIC_IP }} << 'EOF'
            set -e

            cd /home/ubuntu

            # Remove old app folder
            rm -rf cloudmaster

            # Clone fresh repo
            git clone https://github.com/theritikbarnwal/cloudmaster.git
            cd cloudmaster

            # Activate global venv or create if missing
            if [ -d "/home/ubuntu/venv" ]; then
              source /home/ubuntu/venv/bin/activate
              pip install -r requirements.txt
            else
              python3 -m venv /home/ubuntu/venv
              source /home/ubuntu/venv/bin/activate
              pip install --upgrade pip
              pip install -r requirements.txt
            fi

            # Restart systemd service
            sudo systemctl restart cloudmaster.service
          EOF
